#!/data/data/com.termux/files/usr/bin/env python

"""
bi12 - entry point for called in /usr/bin/
"""

import sys
import bible
import part

__version__ = "0.6"


def main():
    """
        main function called for enter in interactive mode
    """
    print("===========================================")
    print("  Baiboly fandikan-teny ny tontolo vaovao")
    print("    Version :", __version__)
    print("===========================================")
    while True:
        command = input(" bi12 > ").lower()
        cmd = command.split(" ")
        # bi book
        parser = bible.bibleParse()
        parser.parse(command)
        if parser.chapter != []:
            print(parser.book.capitalize())
            for i, chap in enumerate(parser.chapter):
                part.parter(parser.book, chap, parser.verset2[i])
        elif cmd[0] == "exit":
            break
        elif cmd[0] == "quit":
            break
        elif cmd[0] == "version":
            print("Version:", __version__)


def view(command):
    """
        view function called for non-interactive mode
    """
    command = command.lower()
    parser = bible.bibleParse()
    parser.parse(command)
    if parser.chapter != 0:
        part.parter(parser.book, parser.chapter, parser.verset2)


if len(sys.argv) == 1:
    main()
else:
    if len(sys.argv) == 2:
        view(sys.argv[1] + " " + sys.argv[2])
    elif len(sys.argv) == 3:
        view(sys.argv[1] + " " + sys.argv[2] + " " + sys.argv[3])
